### ISSUE TITLE
Change ASTROODA to MMODA

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-container#2]
After https://github.com/oda-hub/mmoda-frontend-module/issues/72 should we adapt everything in the container? 
@volodymyrss

Some things will work as far as github resolves old names properly. But module names should be changed in utility scripts, it guess (also in frontend-chart)

Offtopic: There is .gitmodules here pointing to the unige repos. Seems that it's not needed.

**Comment by dsavchenko** [comment]
see also https://github.com/oda-hub/frontend-chart/pull/21

**Comment by motame** [comment]
Indeed, yes !
The drupal module astrooda is renamed into mmoda.
And the Drupal theme bootstrap_astrooda is renamed into bootstrap_mmoda.

You can start from scratch and take the four components from github.
The 4 heads in github compose a consistent self-contained system.

If you want to keep an existing instance, I recommend first uninstalling astrooda (main module and instrument modules):
- Disable all modules :
`$ drush dis -y astrooda`
- Uninstall all instrument modules (pmu short of pm-uninstall):
`$ drush pmu -y astrooda_antares astrooda_gw astrooda_isgri astrooda_jemx astrooda_legacysurvey astrooda_polar astrooda_spi_acs`
- Then uninstall the main module astrooda
`$ drush pmu -y astrooda`

Then you can remove astrooda from the file system:
`$ rm -rf sites/all/modules/astrooda`

In a second time, put a copy of mmoda in sites/all/modules.
Install and enable mmoda and instrument modules.
It can be done in one shot:
`$ drush en -y mmoda_antares mmoda_gw mmoda_isgri mmoda_jemx mmoda_legacysurvey mmoda_polar mmoda_spi_acs`

In a similar way, put a copy of bootstrap_mmoda in sites/all/themes, then enable the new theme:
`$ drush en -y bootstrap_mmoda`
Set the new theme as default
`$ drush vset theme_default bootstrap_mmoda`
Clear all caches to avoid surprises:
`$ drush cc all`

You can then disable and delete the old theme:
`$ drush dis -y bootstrap_astrooda`
Set the new theme as default
`$ rm -rf sites/all/themes/bootstrap_astrooda`

**Comment by motame** [comment]
Sorry closed by mistake
